spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ordemservico?createDatabaseIfNotExist=true&serverTimeZone=UTC
        username: ${DB_USER:gustavo}
        password: ${DB_PASSWORD:}
    jpa:
        show-sql: true
